[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "http://www.tinyhouse.investments/*"
  to = "https://tinyhouse.investments/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tinyhouse.investments/*"
  to = "https://tinyhouse.investments/:splat"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
