import { MetadataRoute } from "next";

const BASE_URL = "https://tinyhouse.investments";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: BASE_URL,
      lastModified: "2026-05-14",
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/marktplatz`,
      lastModified: "2026-05-14",
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/so-funktioniert-es`,
      lastModified: "2026-03-01",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/renditemodell`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/steuervorteil`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/galerie`,
      lastModified: "2026-02-01",
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${BASE_URL}/partner`,
      lastModified: "2026-02-01",
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${BASE_URL}/impressum`,
      lastModified: "2026-03-01",
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: `${BASE_URL}/datenschutz`,
      lastModified: "2026-03-01",
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: `${BASE_URL}/agb`,
      lastModified: "2026-03-01",
      changeFrequency: "yearly",
      priority: 0.2,
    },
    {
      url: `${BASE_URL}/wissen`,
      lastModified: "2026-04-14",
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/tiny-house-als-kapitalanlage`,
      lastModified: "2026-05-15",
      changeFrequency: "monthly",
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/wissen/kapitalanlage`,
      lastModified: "2026-05-15",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/afa-abschreibung`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/direktinvestment`,
      lastModified: "2026-04-14",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-als-rendite`,
      lastModified: "2026-04-14",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/steuerberater-finden`,
      lastModified: "2026-04-26",
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/wissen/host-werden`,
      lastModified: "2026-04-26",
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/hosts`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/konfigurator`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${BASE_URL}/rechner/iab`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/rechner/rendite`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-finanzierung`,
      lastModified: "2026-04-26",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-genehmigung`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/ferienimmobilie-steuer`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-airbnb`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-standorte`,
      lastModified: "2026-04-26",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/passive-einnahmen-immobilien`,
      lastModified: "2026-04-13",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-kaufen-checkliste`,
      lastModified: "2026-04-26",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/7g-tiny-house-investment`,
      lastModified: "2026-04-15",
      changeFrequency: "monthly",
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/wissen/iab-tiny-house`,
      lastModified: "2026-05-06",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-steuern-sparen`,
      lastModified: "2026-04-15",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-rendite-rechner`,
      lastModified: "2026-04-15",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/solaranlage-alternative`,
      lastModified: "2026-04-28",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/pv-anlage-als-kapitalanlage`,
      lastModified: "2026-04-23",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/pv-direktinvestment-alternative`,
      lastModified: "2026-05-20",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-kaufen`,
      lastModified: "2026-04-29",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-kaufen-mit-grundstueck`,
      lastModified: "2026-04-29",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-steuer-risiken`,
      lastModified: "2026-05-06",
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/wissen/senioren`,
      lastModified: "2026-05-15",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/aerzte`,
      lastModified: "2026-05-22",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/freiberufler`,
      lastModified: "2026-05-22",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/it-freelancer`,
      lastModified: "2026-05-22",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/unternehmer`,
      lastModified: "2026-05-22",
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/wissen/zielgruppen`,
      lastModified: "2026-05-22",
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-altersvorsorge`,
      lastModified: "2026-05-23",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/wissen/rentenlucke-schliessen`,
      lastModified: "2026-05-23",
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/wissen/tiny-house-vs-etf-altersvorsorge`,
      lastModified: "2026-05-23",
      changeFrequency: "monthly",
      priority: 0.8,
    },
  ];
}
